# permissions for end users to view kataconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kataconfig-viewer-role
rules:
- apiGroups:
  - kataconfiguration.openshift.io
  resources:
  - kataconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kataconfiguration.openshift.io
  resources:
  - kataconfigs/status
  verbs:
  - get
