apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-sandboxed-containers-rules
  namespace: openshift-sandboxed-containers-operator
spec:
  groups:
    - name: kata_monitor_rules
      rules:
      - record: cluster:kata_monitor_running_shim_count:sum
        expr: sum(kata_monitor_running_shim_count)
